import random
from faker import Faker
import psycopg2
from datetime import datetime

fake = Faker('pt_BR')

DIAS_31 = [1,3,5,7,8,10,12]
ELO_RANGE = 200
NUM_USUARIOS = 20
NUM_DIAS = 137
NUM_CLUBES = 5
TIPOS_DE_PARTIDA = ["Bullet", "Rápida","Padrão","Xadrez960","Por correspondência"]
CARGOS = ["Administrador", "Membro"]
# Funcoes auxiliares


def usuario():
    usuarios = []
    for i in range(1,NUM_USUARIOS+1):
        elo = 1000
        nome_usuario = fake.user_name()
        id = i
        usuarios.append((id,nome_usuario,elo))
    
    return usuarios
    
def historico(usuarios):
    mes = 1
    historico = []
    id_partida = 1
    elo = []
    for u in usuarios:
        elo.append([u[2],u[0]])
    elo.sort()
    for d in range (1,NUM_DIAS+1):
        for p in range(random.randint(1,4) * NUM_USUARIOS): 
            p1 = random.randint(1,len(elo) - 1)
            p2 = p1-1 if elo[p1-1][0] - elo[p1][0] < ELO_RANGE else p1+1
            id_p1 = elo[p1][1]
            id_p2 = elo[p2][1]
            res_esperado_p1 = 1/(1+10**((elo[p2][0]-elo[p1][0])/400))
            res_esperado_p2 = 1/(1+10**((elo[p1][0]-elo[p2][0])/400))
            res = random.randint(0,1)
            if res == 0 :
                ganhador = random.choice((p1,p2))
                if ganhador == p1:
                    res_p1 = 1
                    res_p1_string = "Vitória"
                    res_p2 = 0
                    res_p2_string = "Derrota"
                else:
                    res_p1 = 0
                    res_p1_string = "Derrota"
                    res_p2 = 1
                    res_p2_string = "Vitória"
            else:
                res_p1 = 0.5
                res_p1_string = "Empate"
                res_p2 = 0.5
                res_p2_string = "Empate"
            
            novo_elo_p1 = round(elo[p1][0] + 15 * (res_p1 - res_esperado_p1),1)
            novo_elo_p2 = round(elo[p2][0] + 15 * (res_p2 - res_esperado_p2),1)
            movimentos = round(random.normalvariate(35,5))
            precisao_p1 = round(random.normalvariate(55,5))
            precisao_p2 = round(random.normalvariate(55,5))
            data = f"{d}/{mes}/{2025}"
            tipo = random.choice(TIPOS_DE_PARTIDA)
            
            historico.append((id_p1,id_p2,id_partida,novo_elo_p1,precisao_p1,movimentos,res_p1_string, data, tipo))
            historico.append((id_p2,id_p1,id_partida,novo_elo_p2,precisao_p2,movimentos,res_p2_string, data, tipo))
            elo[p1][0] = novo_elo_p1
            elo[p2][0] = novo_elo_p2
            
        if d == 28 and mes == 2:
            mes = 3
        elif d == 31 and mes in DIAS_31:
            mes+= 1
        elif d == 30:
            mes+= 1
    return historico
            

def clubes():
    clubes = []
    for clube in range(1,NUM_CLUBES + 1):
        id_clube = clube
        nome_clube = fake.village()
        data_criacao = fake.date_this_year(before_today= True)
        clubes.append((id_clube,nome_clube,data_criacao))
        
def clube_usuario(usuarios,clubes):
    clube_usuario = []
    for c in clubes:
        fundador = random.choice(usuarios[0])
        clube_usuario.append((c[0],fundador,c[2],"Fundador"))
        for u in range(1,abs(random.normalvariate(NUM_USUARIOS/5,NUM_USUARIOS/15))):
            
            data = fake.date_between_dates(c[2])

def inserir_no_banco():
    try:
        conn = psycopg2.connect(
            host="db.kyxedeqogvcoshwlxdie.supabase.co",
            database="postgres",
            user="postgres",
            password="aMUSGl7r02YQ6eKF"
        )
        cursor = conn.cursor()
        tabelas = [
            "usuario", "partidas", "historico", "amizades", "clubes", "clube_usuario"
        ]
        for tabela in tabelas:
            cursor.execute(f"DROP TABLE IF EXISTS {tabela} CASCADE;")
        
        comandos_sql = [
            """
            CREATE TABLE usuario (
                id BIGINT NOT NULL PRIMARY KEY,
                nome_usuario VARCHAR NOT NULL,
                elo BIGINT NULL
            );
            """,
            """
            create table historico (
            id_usuario bigint generated by default as identity not null,
            id_partida bigint not null,
            id_oponente bigint,
            precisao real null,
            movimentos bigint null,
            resultado boolean null,
            data DATE,
            constraint historico_pkey primary key (id_usuario, id_partida, id_oponente),
            constraint historico_id_partida_fkey foreign KEY (id_partida) references partidas (id_partida),
            constraint historico_id_usuario_fkey foreign KEY (id_usuario) references usuario (id),
            constraint historico_id_oponente_fkey foreign KEY (id_oponente) references usuario (id)
            );
            """,
            """
            create table amizades (
            id_1 bigint generated by default as identity not null,
            id_2 bigint not null,
            data date null default now(),
            constraint amizades_pkey primary key (id_1, id_2),
            constraint amizades_id_1_fkey foreign KEY (id_1) references usuario (id),
            constraint amizades_id_2_fkey foreign KEY (id_2) references usuario (id)
            );
            """,
            """
            create table clubes (
            id_clube bigint generated by default as identity not null,
            nome_clube character varying not null,
            data_criacao date null,
            constraint clubes_pkey primary key (id_clube)
            );
            """,
             """
            create table clube_usuario (
            id_clube bigint generated by default as identity not null,
            id_usuario bigint not null,
            data_join date null,
            cargo character varying null,
            constraint clube_usuario_pkey primary key (id_clube, id_usuario),
            constraint clube_usuario_id_clube_fkey foreign KEY (id_clube) references clubes (id_clube),
            constraint clube_usuario_id_usuario_fkey foreign KEY (id_usuario) references usuario (id)
            );
            """
            
        ]    
        
        for comando in comandos_sql:
            cursor.execute(comando)
        conn.commit()
    except Exception as e:
        print(f"Erro: {e}")
        return False

    finally:
        if 'conn' in locals():
            conn.close()

a = usuario()
for e in a:
    print(e)
p = historico(a)
print(p)